### ISSUE TITLE
Crashes after make changes to the original buildings

### ISSUE THREAD

**Issue by Frostlock-Z** [flowtsohg/war3-objectdata#1]
After I add more units to the Trains(utra) section of the original orc bildings, the error occurs.
It seems I cannot modify any original units or buildings.

Error: Failed to get an Ability prop: ogre utra
    at objectLoader (F:\Programming\War3\Project_Relax\node_modules\war3-objectdata\dist\cjs\container.js:26:19)
    at loadObject (F:\Programming\War3\Project_Relax\node_modules\war3-objectdata\dist\cjs\container.js:66:5)
    at Object.load (F:\Programming\War3\Project_Relax\node_modules\war3-objectdata\dist\cjs\container.js:71:9)
    at ObjectData.load (F:\Programming\War3\Project_Relax\node_modules\war3-objectdata\dist\cjs\objectdata.js:27:25)
    at loadObjectData (F:\Programming\War3\Project_Relax\node_modules\war3-transformer\dist\objectdata.js:39:20)
    at runTransformer (F:\Programming\War3\Project_Relax\node_modules\war3-transformer\dist\transformer.js:63:54)
    at loadTransformer (F:\Programming\War3\Project_Relax\node_modules\typescript-to-lua\dist\transpilation\transformers.js:123:27)
    at loadTransformersFromOptions (F:\Programming\War3\Project_Relax\node_modules\typescript-to-lua\dist\transpilation\transformers.js:86:55)
    at getTransformers (F:\Programming\War3\Project_Relax\node_modules\typescript-to-lua\dist\transpilation\transformers.js:15:37)
    at getProgramTranspileResult (F:\Programming\War3\Project_Relax\node_modules\typescript-to-lua\dist\transpilation\transpile.js:67:61)
Error: Command failed: tstl -p tsconfig.json
    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at compileMap (F:\Programming\War3\Project_Relax\scripts\utils.ts:126:11)
    at main (F:\Programming\War3\Project_Relax\scripts\test.ts:6:28)
    at Object.<anonymous> (F:\Programming\War3\Project_Relax\scripts\test.ts:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (F:\Programming\War3\Project_Relax\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (F:\Programming\War3\Project_Relax\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)

**Comment by Frostlock-Z** [comment]
I am working on a war3 reforge map.

**Comment by flowtsohg** [comment]
There are fundamental issues with the entire design when it comes to more complex ability data with levels and such, mostly because I learned about this stuff from Retera and others as I wrote the code and reshaped it, and honestly I still can't say I know all the specifics well enough to make something that isn't broken for some objects/fields - some because the object data itself has consistency issues as all wc3 data, and some because I don't really understand how the data connects between the different files.

Either way, I am not planning to work on any wc3 related code in the foreseeable future, sorry.

**Comment by Frostlock-Z** [comment]
Thanks for the response! Still appreciate your work！

**Comment by Eonfuzz** [comment]
Been trying to use a few experimental branches of wc3ts and ran into this problem here, only to see you have or are leaving us.
Sad to see you go Ghostwolf, be safe out there mate! ~Boar
